###########################################################
#                                                         #
#                     Automations                         #
#                                                         #
#    https://www.home-assistant.io/docs/automation        #
#  https://www.home-assistant.io/docs/automation/editor   #
# https://www.home-assistant.io/docs/automation/examples  #
#                                                         #
#  This is in the old format. I used it because editor    #
# removes comments and don't support data templates       #
###########################################################
###########################################################
#                                                         #
#                       Doors                             #
#                                                         #
###########################################################
# Trigger for turning on one light when exit door is open
- alias: Turn on light when exit door is open
  # Initial state after home assistant restart
  # initial_state: 'off'
  # To hide this automation from web frontend set this to true
  # hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.exit_door
    to: 'on'
  #create condition to trigger
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: -01:00:00
      - condition: sun
        before: sunrise
        before_offset: 01:00:00
  action:
    service: light.turn_on
    entity_id: light.aqara_hall

# Trigger for turning off one light after 5 minutes than exit door is open 
- alias: Turn off light 3 minutes after exit door is open
  trigger:
    platform: state
    entity_id: binary_sensor.exit_door
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    entity_id: light.aqara_hall
###########################################################
#                                                         #
#                     Switches                            #
#                                                         #
###########################################################    
- alias: Aqara Double Switch - Left
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0002c61053'
  condition:
    condition: template
    value_template: "{{ 'left' == trigger.payload_json.click }}"
  action:
    entity_id: light.innr
    service: light.toggle
      
- alias: Aqara Double Switch - Right
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0002c61053'
  condition:
    condition: template
    value_template: "{{ 'right' == trigger.payload_json.click }}"
  action:
    entity_id: light.go
    service: light.toggle    
###########################################################
#                                                         #
#                   Notifications                         #
#                                                         #
###########################################################
# Trigger for sending a notification when exit door is open
- alias: iOS notification when exit door is opened
  trigger:
    platform: state
    entity_id: binary_sensor.exit_door
    to: 'on'  
  action:
    service: notify.ios_felipes_iphone
    data:
      title: "HomeAssistant - Exit Door"
      message: "Exit Door Opened"
      data:
        push:
          category: 'exit_door'
        #this doesn't work and I don't know why. I needed to create another automation and in ios.yaml a call to the automation.
        # action_data:
          # entity_id: light.innr
          # service: light.turn_on
          
# This is the notification button action (from exit_door)
- alias: Push exit_door Action Light On
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: EXIT_DOOR_OPEN
  action:
    entity_id: light.innr
    service: light.turn_on
###########################################################
#                                                         #
#                    Shell Commands                       # #                                                         #
###########################################################
- alias: Create MQTT Graph
  initial_state: true
  trigger:
    platform: sun
    event: sunset
  action:
    service: shell_command.mosquitto_pub_mqtt_graph
###########################################################
#                                                         #
#                      Themes                             #
#                                                         #
###########################################################
# Sunset
- alias: Random Darker Theme At Sunset
  initial_state: true
  trigger:
    platform: sun
    event: sunset
  action:
    - service: frontend.set_theme
      data_template:
        name: '{{ ["darkred", "darkcyan", "midnight", "darkorange", "darkblue", "oxforddark", "teal"] | random  }}'

# Sunrise
- alias: Random Lighter Theme At Sunrise
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: frontend.set_theme
      data_template:
        name: '{{ ["default", "oxfordblue", "carbongreen", "minimal", "stormy_hues", "vintage"] | random  }}'
