###########################################################
#                                                         #
#               Main Configuration File                   #
#                                                         #
#            https://home-assistant.io/docs/              #
#                                                         #
###########################################################
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: !secret my_unit_system
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml
  # packages folder
  # packages: !include_dir_named packages

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret hass_pass
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

#Enables HA REST API
api:
  
# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver #until is configured

#MQTT Config | https://www.home-assistant.io/components/mqtt/
mqtt:
  # This settings are for the Home Assistant embedded MQTT broker:
  discovery: true
  password: !secret hass_pass 
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  #MOSQUITTO broker: https://randomnerdtutorials.com/how-to-install-mosquitto-broker-on-raspberry-pi/  
  # broker: localhost
  # discovery: true
    
#duckdns component: check https://www.duckdns.org    
duckdns:
  domain: !secret domain
  access_token: !secret duck_access_token

###########################################################
#                                                         #
#               Frontend Modifications                    #
#                                                         #
###########################################################
# Enables the frontend | https://www.home-assistant.io/components/frontend/
frontend:
  themes: !include themes.yaml
     
# Allows displaying links in frontend | https://www.home-assistant.io/components/weblink/
# weblink:
    
# Allows adding panels to frontend in a iframe way without having to write the container code | https://www.home-assistant.io/components/panel_iframe/
panel_iframe:
  zigbee_graph:
    title: 'Zigbee Graph'
    url: '/local/zigbee_graph.html'
    icon: mdi:graphql
    
# Allows adding panels to frontend running a full html page. Need a container code | https://www.home-assistant.io/components/panel_custom/
# panel_custom:
      
# Enables configuration UI in frontend | https://www.home-assistant.io/components/config/
config:

# Allows you to issue voice commands from the frontend in enabled browsers | https://www.home-assistant.io/components/conversation/
# conversation:

# Enables support for tracking state changes over time | https://www.home-assistant.io/components/history/
history:
  include:
    domains:
      - sensor
      - switch
      - light

# View all events in a logbook | https://www.home-assistant.io/components/logbook/
logbook:

###########################################################
#                                                         #
#                     Components                          #
#                                                         #
###########################################################
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors | https://www.home-assistant.io/components/sensor/
sensor:
  # Weather prediction. The weather forecast is delivered by the Norwegian Meteorological Institute and the NRK
  - platform: yr
    name: 'YR Weather'
    forecast: 48
    monitored_conditions:
      - symbol
      - temperature
      - precipitation
      - humidity
      - windSpeed

# Keeps track of system switches. Need always a platform | https://www.home-assistant.io/components/switch      
switch: 
  platform: command_line
  switches:
    graphviz:
     command_on: "mosquitto_pub -V mqttv311 -u homeassistant -P madi -t 'zigbee2mqtt/bridge/networkmap' -m graphviz"
  
# Weather platform component | https://www.home-assistant.io/components/weather/
# check a nice weather card https://www.reddit.com/r/homeassistant/comments/8dnxf0/easy_instructions_for_a_custom_weather_card/
weather:
  - platform: ipma
    name: 'IPMA Weather'

# Text to speech | https://www.home-assistant.io/components/tts/
tts:
  - platform: google
    

# Media player settings | https://www.home-assistant.io/components/media_player/
media_player:

# Makes it possible to send notifications to a wide variety of platforms | https://www.home-assistant.io/components/notify
notify:
  - platform: ios #enable ios notifications

# Amazon Echo integration | https://www.home-assistant.io/components/alexa/ 
alexa:

###########################################################
#                                                         #
#                     Includes                            #
#                                                         #
###########################################################
# zone: !include zones.yaml
ios: !include ios.yaml
intent_script: !include alexa_intent_scripts.yaml    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml